# Generated by Django 3.2.7 on 2022-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensional', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
